# Generated by Django 4.1.7 on 2023-02-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='features_image',
            field=models.ImageField(blank=True, default='static/src/placeholder-image.png', upload_to='static/src/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
