# Generated by Django 4.1.6 on 2023-02-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_tag_post_category_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
