# Generated by Django 4.1.7 on 2023-02-26 03:57

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_features_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=news.models.ColorField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='features_image',
            field=models.ImageField(blank=True, default='static/src/images/default.png', upload_to='static/src/images'),
        ),
    ]
