# Generated by Django 4.1.7 on 2023-02-26 04:00

from django.db import migrations
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_color_alter_post_features_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=news.models.ColorField(null=True),
        ),
    ]
