# Generated by Django 4.1.7 on 2023-02-26 04:57

from django.db import migrations
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=news.models.ColorField(blank=True),
        ),
    ]
