# Generated by Django 4.1.7 on 2023-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='features_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='news'),
        ),
    ]
