# Generated by Django 4.1.7 on 2023-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_features_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='features_image',
            field=models.ImageField(default='default.png', upload_to='news'),
        ),
    ]
